### ISSUE TITLE
Deadlink

### ISSUE THREAD

**Issue by Doodoune** [akeneo/sfcc-helpcenter#45]
https://help.akeneo.com/sfcc/v19/articles/where-product-association.html

Link "Salesforce documentation" raise an ERROR 404: https://documentation.b2c.commercecloud.salesforce.com/DOC2/topic/com.demandware.dochelp/Products/LinkingProducts.html?resultof=%22%50%72%6f%64%75%63%74%22%20%22%70%72%6f%64%75%63%74%22%20%22%6c%69%6e%6b%22%20

![screenshot_2](https://user-images.githubusercontent.com/34027529/75454687-19acf600-5976-11ea-842d-8674eeb1aaf5.png)

**Comment by Doodoune** [comment]
Idem on https://help.akeneo.com/sfcc/v19/articles/06-categories-configuration.html

ERROR 404: https://documentation.b2c.commercecloud.salesforce.com/DOC2/topic/com.demandware.dochelp/Products/Classificationvsprimarycategory.html?resultof=%22%70%72%69%6d%61%72%79%22%20%22%63%61%74%65%67%6f%72%79%22%20

![screenshot_3](https://user-images.githubusercontent.com/34027529/75454881-70b2cb00-5976-11ea-89e5-d4244cf17eb9.png)

**Comment by arduibag** [comment]
Hi Elo, I fixed this issues and it will be deployed with some english fixes this week.

**Comment by arduibag** [comment]
Deployed.
